### ISSUE TITLE
Wymowa stopni(e).

### ISSUE THREAD

**Issue by lukas125p** [tureq80/Raspbbery-pi-pogodynka#1]
Nie myślałeś nad zmianą wymowy temperatury zależnie czy są to stopnie czy stopni?
Niezbyt pięknie brzmi, że temperatura wynosi 5 stopień.

**Comment by tureq80** [comment]
Nie wiem gdzie masz problem z wymową jeżeli używasz skryptu ktory jest podany to za każdym razem jak czyta google "Aktualna pogoda to 5°C..." wymawia prawidłowo: 5 stopni celcjusza lub 1 stopień celcjusza. 

Musi być koniecznie użyty w tekście znak np.: 5°C

**Comment by tureq80** [comment]
Oto przykład otwórz to w zwykłej przeglądarce np. google chrome http://translate.google.com/translate_tts?ie=UTF-8&total=1&idx=0&textlen=32&client=tw-ob&q=24%C2%B0C&tl=Pl-pl

oraz 

http://translate.google.com/translate_tts?ie=UTF-8&total=1&idx=0&textlen=32&client=tw-ob&q=1%C2%B0C&tl=Pl-pl

Jeśli uważasz że źle wymawia to mamy inne Internety :)

**Comment by lukas125p** [comment]
No to chyba mamy jednak inne. Tak wymawia u mnie: http://www.supershare.pl/?d=1A933EC12
Zmodyfikowałem nieco kolejność, ale myślę, że to nie wpływa na sposób wymawiania stopni.

**Comment by lukas125p** [comment]
Tak to wygląda u mnie:
`
echo 'Aktualna pogoda to '.$temp2.'°C, ';

echo '...,  ciśnienie wynosi '.$cisnienie2.'hPa. ';

echo $chmury; 
`

**Comment by lukas125p** [comment]
Ok problem rozwiązany. Okazało się, że nie miałem ustawionego kodowania na Raspberry. sudo raspi-config->internatiolisation-> change locale->utf-8. Poza tym wszystko gra :+1:

**Comment by tureq80** [comment]
Wlasnie chcialem zapytac czy masz odpowiedni region jezyk wybrany w rpi. Widze ze poradziles sobie wiec teraz to juz tylko fantazja wykorzystania pomysłu. Mam jeszcze skrypt na aktualne mecze wybranej druzyny np Bayern Munchen o której i kiedy odbędzie sie mecz.
